# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Developer utility toolkit — encoding, hashing, formatting, and generation tools for the terminal, browser, and desktop"
  homepage "https://github.com/StanMarek/forge"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/StanMarek/forge/releases/download/v0.1.0/forge_0.1.0_darwin_amd64.tar.gz"
    sha256 "7d4e620d123b291c0845cc4eac26c9fcbaaf0428d0936511a0ccc7f1a1f13a42"

    define_method(:install) do
      bin.install "forge"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/StanMarek/forge/releases/download/v0.1.0/forge_0.1.0_darwin_arm64.tar.gz"
    sha256 "b9e101f66d6a7249de13c0cd263dfdccb52e0fab393e7a232af29d49362a5311"

    define_method(:install) do
      bin.install "forge"
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
